version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - new_app

networks:
  new_app:
    driver: bridge
